# Generated by Django 3.1.2 on 2021-03-31 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210331_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='place',
        ),
        migrations.AddField(
            model_name='temperature',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.place'),
            preserve_default=False,
        ),
    ]
